TechnicalCourses/urls.py
from django.urls import path
from . import views

app_name = 'TechnicalCourses'
urlpatterns = [
    path('<int:course_id>/', views.detail, name="detail"),
    path('', views.Courses, name='home-page'),
    path('<int:course_id>/yourchoice/', views.yourchoice, name='yourchoice')
]

Website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('TechnicalCourses.urls')),
    path('employees/', include('webapp.urls'))
]

webapp/urls.py
from django.urls import path
from . import views


app_name = 'webapp'
urlpatterns = [
    path('', views.employeeList.as_view())
]

TechnicalCourses/models.py
from django.db import models
import datetime
from django.utils import timezone


class Allcourses(models.Model):
    coursename = models.CharField(max_length=200)
    insname = models.CharField(max_length=100)
    startedfrom = models.DateTimeField('Started from')
    
    def __str__(self):
        return self.coursename
    
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.startedfrom <= now
    

class details(models.Model):
    course = models.ForeignKey(Allcourses, on_delete=models.CASCADE)
    ct = models.CharField(max_length=500)
    your_choice = models.BooleanField(default=False)
    
    def __str__(self):
        return str(self.ct)

webapp/models.py
from django.db import models

class employees(models.Model):
    firstname = models.CharField(max_length=10)
    lastname = models.CharField(max_length=10)
    emp_d = models.IntegerField()
    
    def __str__(self):
        return self.firstname

TechnicalCourses/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Allcourses
from django.template import loader


def Courses(request):
    ac = Allcourses.objects.all()
    template = loader.get_template('TechnicalCourses/Courses.html')
    context = {
        'ac': ac,
    }
    return HttpResponse(template.render(context, request))


def detail(request, course_id):
    course = get_object_or_404(Allcourses, pk=course_id)
    
    return render(request, 'TechnicalCourses/detail.html', {'course': course})


def yourchoice(request, course_id):
    course = get_object_or_404(Allcourses, pk=course_id)
    try:
        selected_ct = course.details_set.get(pk=request.POST['choice'])
    except (KeyError, Allcourses.DoesNotExist):
        return render(request, 'Allcourses/detail.html', {
            'course': course,
            'error_message': "Select valid option"
        })
    else:
        selected_ct.your_choice = True
        selected_ct.save()
        return render(request, 'TechnicalCourses/detail.html', {'course': course})

webapp/views.py
from django.shortcuts import render

from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .models import employees
from .serializers import employeesSerializer


class employeeList(APIView):
    
    def get(self, request):
        employees1 = employees.objects.all()
        serializer = employeesSerializer(employees1, many=True)
        return Response(serializer.data)
    
    def post(self):
        pass

TechnicalCourses/templates/TechnicalCourses/Courses.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<h1>Welcome to Edureka!</h1>

<ol>
    {% for x in ac %}
    <li><a href="/{{x.id}}/">{{x.coursename}}</a></li>
    {% endfor %}
</ol>

TechnicalCourses/templates/TechnicalCourses/detail.html
{% if course.pk is 1 %}
<h1><a href="https://www.edureka.co/data-science-python-certification-course">{{course.coursename}}</a></h1>
<h2>{{course.insname}}</h2>
<ul>
    {% for x in Allcourses.set.all %}
        <li>{{ x.ct }}</li>
    {% endfor %}
</ul>
{% elif course.pk is 2 %}
<h1><a href="https://www.edureka.co/java-j2ee-training-course">{{course.coursename}}</a></h1>
<h2>{{course.insname}}</h2>
{% else %}
<h1>{{course.coursename}}</h1>
<h2>{{course.insname}}</h2>
{% endif %}

{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'TechnicalCourses:yourchoice' course.id %}" method="post">
    {% csrf_token %}
    {% for choice in course.details_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.ct }}</label><br>
    {% endfor %}
    <input type="submit" value="Submit">
</form>